### ISSUE TITLE
Release 1.13

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/jollyroger#2]
### Descriptive summary
Version: 1.13
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonik 

To Verify/Review:
- #162 MARC to CSV Mapping: add 79X, 245 $c

**Comment by gamontoya** [comment]
@lsitu This can be pushed to prod.

**Comment by rstanonik** [comment]
Scheduled to deploy to production tomorrow morning at 6:00am

**Comment by lsitu** [comment]
@gamontoya Yes, I think we can deploy it to prod at anytime. But it won't help much without damsmanager new release 2.64 that will extract the MODS fields and convert it to CSV.

**Comment by rstanonik** [comment]
It deployed this morning to prod.

**Comment by lsitu** [comment]
Thanks @rstanonik. It looks good.
