### ISSUE TITLE
Release 1.14

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/jollyroger#4]
### Descriptive Summary

- Version: 1.14
- Release Manager: @lsitu
- Product Owner and Reviewers: @gamontoya
- Operations: @jhriv or @rstanonik 

--- 
### To Verify/Review

- [x] Support 9 digit bibs for MARC/MODS Import #3

**Comment by lsitu** [comment]
@gamontoya I've deployed JollyRoger release 1.14 to staging and it's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Approved for prod for a release on Tuesday morning.

**Comment by lsitu** [comment]
@rstanonik / @jhriv I've merged release 1.14 to master branch and it's ready for prod now. Thanks.

**Comment by gamontoya** [comment]
@rstanonik Please release on Tuesday, during the regular service window.

**Comment by lsitu** [comment]
@rstanonik Can we deploy JollyRoger release 1.14 to prod along with DAMS Manager [Release 2.67](https://github.com/ucsdlib/damsmanager/issues/260) tomorrow morning as well? Thanks.

**Comment by rstanonik** [comment]
I scheduled jollyroger to deploy to prod tomorrow morning too.

**Comment by rstanonik** [comment]
jollyroger deployed this morning at 6:00am and the tomcat was restarted afterward.

**Comment by lsitu** [comment]
Thanks @rstanonik .
